default: &default
  adapter: postgresql
  encoding: unicode
  database: peck
  pool: 5
  username: peck
  password: derpderp
  host: peckdb.coo37zvij2ce.us-west-2.rds.amazonaws.com
  port: 5432

development:
  adapter: postgresql
  encoding: unicode
  database: peck
  pool: 5
  username: peck
  password: derpderp
  host: peckdb.coo37zvij2ce.us-west-2.rds.amazonaws.com
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  database: peck
  pool: 5
  username: peck
  password: derpderp
  host: peckdb.coo37zvij2ce.us-west-2.rds.amazonaws.com
  port: 5432

production:
  adapter: postgresql
  encoding: unicode
  database: peck
  pool: 5
  username: peck
  password: derpderp
  host: peckdb.coo37zvij2ce.us-west-2.rds.amazonaws.com
  port: 5432
